[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi #feature/proton-picosdk-support
board = proton
board_build.pio = src/dshot.pio
framework = picosdk
custom_sdk_components = 
    hardware_flash
    hardware_xip_cache
build_flags = 
    -I "${platformio.packages_dir}/framework-picosdk/src/rp2_common/hardware_xip_cache/include"
    -D PICO_FLASH_SIZE_BYTES=16777216
build_src_flags = -O0 -W -Wno-unused-parameter -Wno-unused-variable -Wno-return-type
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
