// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// dshot //
// ----- //

#define dshot_wrap_target 0
#define dshot_wrap 6
#define dshot_pio_version 0

#define dshot_offset_entry 0u

static const uint16_t dshot_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xe04f, //  1: set    y, 15
    0x6021, //  2: out    x, 1
    0x1a25, //  3: jmp    !x, 5           side 1 [2]
    0x1a06, //  4: jmp    6               side 1 [2]
    0xb242, //  5: nop                    side 0 [2]
    0x1282, //  6: jmp    y--, 2          side 0 [2]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program dshot_program = {
    .instructions = dshot_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = dshot_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config dshot_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + dshot_wrap_target, offset + dshot_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

#include "hardware/clocks.h"
static inline void dshot_program_init(PIO pio, uint sm, uint offset, uint pin, float clk_div) {
    pio_sm_config c = dshot_program_get_default_config(offset);
    sm_config_set_sideset_pins(&c, pin);
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // false = shift left (MSB first), false = autopull off, 32 = threshold
    sm_config_set_out_shift(&c, false, false, 32); 
    sm_config_set_clkdiv(&c, clk_div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

